### ISSUE TITLE
v2.x.x

### ISSUE THREAD

**Issue by pixelass** [pixelass/react-stickyroll#363]
Planned features:

* [x] Stickyroll hook
  * [x] factor
  * [x] throttle
  * [x] `useAnchors` hook
* [ ] Stickyroll component
  * [x] integrate Stickyroll hook
  * [ ] optionally use smooth scrolling
  * [x] optionally snap to pages
* [ ]  Stickyroll decorators
  * [ ] deprecate
* [x]  Stickyroll utils
  * [x] scrollTo
* [x] replace patternplate for storybook

**Demos:**

| Name | Type |  Live Demo |
|-------|------|------------|
| smooth scrolling | property | https://codesandbox.io/s/stickyroll-snappy-ghi4d |
| snap to pages | property | https://codesandbox.io/s/stickyroll-snappy-ghi4d |
| `useAnchors` | hook | https://codesandbox.io/s/stickyroll-snappy-ghi4d |

**Comment by gurkerl83** [comment]
Hi, I tried using sticky-roll a while ago, very nice component, back then I used the hook variant. Looking at the draft for a second you did a huge refactor of the code base. Is the feature to some extent stable and what is your plan or timeframe releasing a second version of sticky-roll. Thx!

**Comment by pixelass** [comment]
We rewrote srtickyroll and v2 is close to being released.
