### ISSUE TITLE
Question: about using throttle with hooks

### ISSUE THREAD

**Issue by teagaal** [pixelass/react-stickyroll#405]
Hi,
Thanks for the work on this library.

I'm using the `useStickyRoll` hook and I'm having trouble implementing the `throttle` util in a function component, and I cannot find examples in the documentation. Any change you could provide a quick example?

Many thanks in advance

**Comment by pixelass** [comment]
Sorry for the late response, looks like I missed the notification.

Throttle is not implemented for `useStickyroll`: https://github.com/stickyroll/react-stickyroll/blob/master/packages/hooks/src/use-stickyroll.ts#L4-L7

If you need this you can open a feature request
