### ISSUE TITLE
[Bug]: @stickyroll/react not available on CSB

### ISSUE THREAD

**Issue by doemser** [pixelass/react-stickyroll#422]
### Contact Details

dominikhautau@gmail.com

### What happened?

Should be available shouldn't it?

### Version

2.x (Default)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pixelass** [comment]
They might be using use a cache, therefore the autocomplete might not pick it up yet, I'm not sure.
You can still install it by simply pressing enter or adding it manually to package.json.

It has been published the npm: https://www.npmjs.com/package/@stickyroll/react
